In [2]:
import pandas

In [5]:
dataset = pandas.read_excel("retail supermarket.xlsx")

In [6]:
import pandas as pd

In [7]:
dataset = pd.read_excel("retail supermarket.xlsx")

In [8]:
dataset

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [9]:
dataset.head(10)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [11]:
dataset.shape

(9994, 13)

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [14]:
result = dataset[(dataset["Sales"] > 500) & (dataset["Quantity"] > 5)]

print(result)

           Ship Mode    Segment        Country           City         State  \
7     Standard Class   Consumer  United States    Los Angeles    California
10    Standard Class   Consumer  United States    Los Angeles    California
16    Standard Class   Consumer  United States        Madison     Wisconsin
27    Standard Class   Consumer  United States   Philadelphia  Pennsylvania
35       First Class  Corporate  United States     Richardson         Texas
...              ...        ...            ...            ...           ...
9879  Standard Class   Consumer  United States  New York City      New York
9925     First Class  Corporate  United States  New York City      New York
9942  Standard Class   Consumer  United States        Anaheim    California
9947    Second Class  Corporate  United States   Indianapolis       Indiana
9948    Second Class  Corporate  United States   Indianapolis       Indiana

      Postal Code   Region         Category Sub-Category     Sales  Quantity  \
7           90032     West       Technology       Phones   907.152         6
10          90032     West        Furniture       Tables  1706.184         9
16          53711  Central  Office Supplies      Storage   665.880         6
27          19140     East        Furniture    Bookcases  3083.430         7
35          75080  Central       Technology       Phones  1097.544         7
...           ...      ...              ...          ...       ...       ...
9879        10035     East        Furniture       Chairs   573.174         7
9925        10035     East  Office Supplies      Binders  1087.936         8
9942        92804     West  Office Supplies      Storage   998.820         9
9947        46203  Central        Furniture       Chairs  1925.880         6
9948        46203  Central  Office Supplies   Appliances  2405.200         8

      Discount     Profit
7          0.2    90.7152
10         0.2    85.3092
16         0.0    13.3176
27         0.5 -1665.0522
35         0.2   123.4737
...        ...        ...
9879       0.1    63.6860
9925       0.2   353.5792
9942       0.0    29.9646
9947       0.0   539.2464
9948       0.0   793.7160

[431 rows x 13 columns]

In [15]:
result = dataset[(dataset["Discount"] > 0.5) | (dataset["Profit"] < 0)]

print(result)

           Ship Mode      Segment        Country             City  \
3     Standard Class     Consumer  United States  Fort Lauderdale
14    Standard Class  Home Office  United States       Fort Worth
15    Standard Class  Home Office  United States       Fort Worth
23      Second Class     Consumer  United States     Philadelphia
27    Standard Class     Consumer  United States     Philadelphia
...              ...          ...            ...              ...
9920  Standard Class    Corporate  United States            Bryan
9921  Standard Class  Home Office  United States            Akron
9931  Standard Class     Consumer  United States   San Bernardino
9937    Second Class    Corporate  United States      Los Angeles
9962     First Class  Home Office  United States          Houston

             State  Postal Code   Region         Category Sub-Category  \
3          Florida        33311    South        Furniture       Tables
14           Texas        76106  Central  Office Supplies   Appliances
15           Texas        76106  Central  Office Supplies      Binders
23    Pennsylvania        19140     East        Furniture       Chairs
27    Pennsylvania        19140     East        Furniture    Bookcases
...            ...          ...      ...              ...          ...
9920         Texas        77803  Central  Office Supplies      Binders
9921          Ohio        44312     East  Office Supplies      Binders
9931    California        92404     West        Furniture    Bookcases
9937    California        90049     West        Furniture       Tables
9962         Texas        77041  Central        Furniture    Bookcases

          Sales  Quantity  Discount     Profit
3      957.5775         5      0.45  -383.0310
14      68.8100         5      0.80  -123.8580
15       2.5440         3      0.80    -3.8160
23      71.3720         2      0.30    -1.0196
27    3083.4300         7      0.50 -1665.0522
...         ...       ...       ...        ...
9920    22.3860         7      0.80   -35.8176
9921     5.7420         3      0.70    -4.5936
9931   683.3320         4      0.15   -40.1960
9937    71.0880         2      0.20    -1.7772
9962   383.4656         4      0.32   -67.6704

[1871 rows x 13 columns]

In [16]:
result = dataset.loc[dataset["Region"] == "East", ["Ship Mode", "Profit"]]

print(result)

           Ship Mode     Profit
23      Second Class    -1.0196
27    Standard Class -1665.0522
28    Standard Class    -7.0532
29    Standard Class    15.5250
30    Standard Class     1.1016
...              ...        ...
9968  Standard Class   331.1910
9969  Standard Class     6.5975
9981     First Class     5.3690
9984  Standard Class    15.1200
9985  Standard Class    16.1240

[2848 rows x 2 columns]

In [19]:
dataset["Profit Margin"] = dataset["Profit"] / dataset["Sales"]

result = dataset[dataset["Profit Margin"] > 0.3]

print(result)

           Ship Mode    Segment        Country           City           State  \
2       Second Class  Corporate  United States    Los Angeles      California
8     Standard Class   Consumer  United States    Los Angeles      California
12    Standard Class   Consumer  United States        Concord  North Carolina
13    Standard Class   Consumer  United States        Seattle      Washington
20      Second Class   Consumer  United States  San Francisco      California
...              ...        ...            ...            ...             ...
9982  Standard Class   Consumer  United States   Grand Rapids        Michigan
9984  Standard Class   Consumer  United States     Long Beach        New York
9986  Standard Class   Consumer  United States    Los Angeles      California
9987  Standard Class  Corporate  United States         Athens         Georgia
9992  Standard Class   Consumer  United States     Costa Mesa      California

      Postal Code   Region         Category Sub-Category    Sales  Quantity  \
2           90036     West  Office Supplies       Labels   14.620         2
8           90032     West  Office Supplies      Binders   18.504         3
12          28027    South  Office Supplies        Paper   15.552         3
13          98103     West  Office Supplies      Binders  407.976         3
20          94109     West  Office Supplies      Binders   22.720         4
...           ...      ...              ...          ...      ...       ...
9982        49505  Central  Office Supplies        Paper   35.560         7
9984        11561     East  Office Supplies       Labels   31.500        10
9986        90008     West       Technology  Accessories   36.240         1
9987        30605    South       Technology  Accessories   79.990         1
9992        92627     West  Office Supplies        Paper   29.600         4

      Discount    Profit  Profit Margin
2          0.0    6.8714         0.4700
8          0.2    5.7825         0.3125
12         0.2    5.4432         0.3500
13         0.2  132.5922         0.3250
20         0.2    7.3840         0.3250
...        ...       ...            ...
9982       0.0   16.7132         0.4700
9984       0.0   15.1200         0.4800
9986       0.0   15.2208         0.4200
9987       0.0   28.7964         0.3600
9992       0.0   13.3200         0.4500

[4145 rows x 14 columns]

In [20]:
result = dataset[(dataset["Category"] == "Furniture") & (dataset["Sub-Category"] != "Chairs")]

print(result)

           Ship Mode      Segment        Country             City       State  \
0       Second Class     Consumer  United States        Henderson    Kentucky
3     Standard Class     Consumer  United States  Fort Lauderdale     Florida
5     Standard Class     Consumer  United States      Los Angeles  California
10    Standard Class     Consumer  United States      Los Angeles  California
24    Standard Class     Consumer  United States             Orem        Utah
...              ...          ...            ...              ...         ...
9962     First Class  Home Office  United States          Houston       Texas
9964    Second Class    Corporate  United States           Newark    Delaware
9980    Second Class     Consumer  United States        Lafayette   Louisiana
9989    Second Class     Consumer  United States            Miami     Florida
9990  Standard Class     Consumer  United States       Costa Mesa  California

      Postal Code   Region   Category Sub-Category      Sales  Quantity  \
0           42420    South  Furniture    Bookcases   261.9600         2
3           33311    South  Furniture       Tables   957.5775         5
5           90032     West  Furniture  Furnishings    48.8600         7
10          90032     West  Furniture       Tables  1706.1840         9
24          84057     West  Furniture       Tables  1044.6300         3
...           ...      ...        ...          ...        ...       ...
9962        77041  Central  Furniture    Bookcases   383.4656         4
9964        19711     East  Furniture  Furnishings    13.4000         1
9980        70506    South  Furniture       Tables    85.9800         1
9989        33180    South  Furniture  Furnishings    25.2480         3
9990        92627     West  Furniture  Furnishings    91.9600         2

      Discount    Profit  Profit Margin
0         0.00   41.9136       0.160000
3         0.45 -383.0310      -0.400000
5         0.00   14.1694       0.290000
10        0.20   85.3092       0.050000
24        0.00  240.2649       0.230000
...        ...       ...            ...
9962      0.32  -67.6704      -0.176471
9964      0.00    6.4320       0.480000
9980      0.00   22.3548       0.260000
9989      0.20    4.1028       0.162500
9990      0.00   15.6332       0.170000

[1504 rows x 14 columns]